# Specify where the dataset comes from moreover the internal folder name if different from the archive name of the dataset
datasource:
    # URL for the archived dataset, e.g: 'https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz'
    dataset_source: ~
    # Top folder name of the archived dataset, e.g: 'flower_photos'
    dataset_name: ~

# Configuration of the CNN model
model:
    convolution:
        # Array with the number of filters for each layer
        layers: [32, 64, 64]
        # Kernel size for the Convolution layers
        kernel: 3
        # Activation function for the Convolution layers
        activation: 'relu'
    dense:
        # Array with the number of nodes for each Dense layer
        layers: [64, 16]
        # Activation function for the Dense layers
        activation: 'relu'
    # One of the supported optimizer function to reduce the losses
    #   See: tensorflow.python.keras.optimizer
    optimizer: 'adam'
    # Output type of model when saved ('tf' or 'h5')
    save_format: 'h5'

# Deployment related configuration
deployment:
    host: ~
    port: ~

# MLflow base configuration
mlflow:
    # The URI where the MLflow server is running
    tracking_uri: ~
    # Name of the group for experiments
    experiment_name: Presentation experiments


